//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vue
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Depot()
        {
            this.livreur = new HashSet<livreur>();
        }

        public Depot(int iddepot, string ville, string adresse, string numtel, int id_user)
        {
            this.iddepot = iddepot;
            this.ville = ville;
            this.adresse = adresse;
            this.numtel = numtel;
            this.id_user = id_user;
        }

        public int iddepot { get; set; }
        public string ville { get; set; }
        public string adresse { get; set; }
        public string numtel { get; set; }
        public int id_user { get; set; }
    
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<livreur> livreur { get; set; }
    }
}
