//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vue
{
    using System;
    using System.Collections.Generic;
    
    public partial class etatcolis
    {
        public etatcolis(int codeetatcolis, int codecolis, int codeetat, int? codelivreur, DateTime date, string commentaire)
        {
            Codeetatcolis = codeetatcolis;
            Codecolis = codecolis;
            Codeetat = codeetat;
            Codelivreur = codelivreur;
            Date = date;
            Commentaire = commentaire;
        }
        public etatcolis() { }
        public int Codeetatcolis { get; set; }
        public int Codecolis { get; set; }
        public int Codeetat { get; set; }
        public Nullable<int> Codelivreur { get; set; }
        public System.DateTime Date { get; set; }
        public string Commentaire { get; set; }
    
        public virtual colis colis { get; set; }
    }
}
