//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vue
{
    using System;
    using System.Collections.Generic;
    
    public partial class expediteur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public expediteur()
        {
            this.colis = new HashSet<colis>();
            this.RecetteExpediteur = new HashSet<RecetteExpediteur>();
        }

        public expediteur(int codeexpediteur, string nomexpediteur, string numtelexpéditeur, string gouvernemant, string adresse, string viille, string codetva, string email, string modepaiement, double fraislivraison, double fraisretour)
        {
            Codeexpediteur = codeexpediteur;
            Nomexpediteur = nomexpediteur;
            Numtelexpéditeur = numtelexpéditeur;
            this.gouvernemant = gouvernemant;
            this.adresse = adresse;
            this.viille = viille;
            Codetva = codetva;
            Email = email;
            Modepaiement = modepaiement;
            Fraislivraison = fraislivraison;
            Fraisretour = fraisretour;
        }

        public int Codeexpediteur { get; set; }
        public string Nomexpediteur { get; set; }
        public string Numtelexpéditeur { get; set; }
        public string gouvernemant { get; set; }
        public string adresse { get; set; }
        public string viille { get; set; }
        public string Codetva { get; set; }
        public string Email { get; set; }
        public string Modepaiement { get; set; }
        public double Fraislivraison { get; set; }
        public double Fraisretour { get; set; }
        public Nullable<int> id_user { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<colis> colis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecetteExpediteur> RecetteExpediteur { get; set; }
    }
}
