//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vue
{
    using System;
    using System.Collections.Generic;
    
    public partial class livreur
    {
        public livreur(int codelivreur, string nomlivreur, string numtel, string numcin, double? fraislivraison, string email, int? iddepot)
        {
            Codelivreur = codelivreur;
            Nomlivreur = nomlivreur;
            Numtel = numtel;
            this.numcin = numcin;
            Fraislivraison = fraislivraison;
            this.email = email;
            this.iddepot = iddepot;
        }
        public livreur(){}
        public int Codelivreur { get; set; }
        public string Nomlivreur { get; set; }
        public string Numtel { get; set; }
        public string numcin { get; set; }
        public Nullable<double> Fraislivraison { get; set; }
        public string email { get; set; }
        public Nullable<int> iddepot { get; set; }
    
        public virtual Depot Depot { get; set; }
    }
}
