//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vue
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecetteExpediteur
    {
        public int Coderecette { get; set; }
        public string datedeb { get; set; }
        public string datefin { get; set; }
        public double montantexpediteur { get; set; }
        public double montantsosciete { get; set; }
        public int nbclislivre { get; set; }
        public int nbcolisretour { get; set; }
        public int Codeexpediteur { get; set; }
    
        public virtual expediteur expediteur { get; set; }
    }
}
