//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vue
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reclamation
    {
        public int Codereclamation { get; set; }
        public string Type { get; set; }
        public string Etat { get; set; }
        public string Commentaire { get; set; }
        public System.DateTime Date { get; set; }
        public int Codecolis { get; set; }
    
        public virtual colis colis { get; set; }
    }
}
