//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vue
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.Depot = new HashSet<Depot>();
        }

        public user(int id_user, string username, string password, string role, long? status)
        {
            this.id_user = id_user;
            this.username = username;
            this.password = password;
            this.role = role;
            this.status = status;
        }

        public int id_user { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string role { get; set; }
        public Nullable<long> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Depot> Depot { get; set; }
    }
}
